//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadGatePayNavieras
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudPago
    {
        public int Id { get; set; }
        public int IdCliente { get; set; }
        public int IdNaviera { get; set; }
        public string NumeroBL { get; set; }
        public string Contenedor { get; set; }
        public decimal MontoEstimado { get; set; }
        public decimal TipoCambio { get; set; }
        public decimal Comision { get; set; }
        public Nullable<decimal> TotalEnBolivianos { get; set; }
        public string EstadoG { get; set; }
        public System.DateTime FechaSolicitud { get; set; }
        public string usuarioRegistro { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public short estado { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Naviera Naviera { get; set; }
    }
}
