//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadGatePayNavieras
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.GateIn = new HashSet<GateIn>();
            this.SolicitudPago = new HashSet<SolicitudPago>();
<<<<<<< HEAD
=======
<<<<<<< HEAD
=======
            this.SolicitudPagoBancoChile = new HashSet<SolicitudPagoBancoChile>();
>>>>>>> 19c75cd (Avance del proyecto: agregados archivos y mejoras)
>>>>>>> 0eb0043 (Actualización: avance del proyecto)
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public string TipoCliente { get; set; }
        public string usuarioRegistro { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public short estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GateIn> GateIn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitudPago> SolicitudPago { get; set; }
<<<<<<< HEAD
=======
<<<<<<< HEAD
=======
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitudPagoBancoChile> SolicitudPagoBancoChile { get; set; }
>>>>>>> 19c75cd (Avance del proyecto: agregados archivos y mejoras)
>>>>>>> 0eb0043 (Actualización: avance del proyecto)
    }
}
