//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadGatePayNavieras
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudPagoBancoChile
    {
        public int Id { get; set; }
        public int IdCliente { get; set; }
        public string NombreSolicitante { get; set; }
        public decimal MontoDolares { get; set; }
        public decimal TipoCambio { get; set; }
        public decimal Comision { get; set; }
        public decimal MontoEnBolivianos { get; set; }
        public string EstadoPago { get; set; }
        public System.DateTime FechaSolicitud { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public string RutaComprobantePago { get; set; }
        public string Observaciones { get; set; }
        public string usuarioRegistro { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public short estado { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
